<template>
  <div>
    <section class="hero is-medium has-text-centered">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">MessageHub</h1>
          <h2 class="subtitle">Transmit secret information safely</h2>
          <div class="hero-buttons">
            <router-link :to="{ name: 'Dashboard' }" class="button is-medium is-primary">Dashboard</router-link>
            <a href="https://github.com/JokeyChen/messagehub" class="button is-medium">View Source</a>
          </div>
        </div>
      </div>
    </section>
    <section class="hero is-primary">
      <div class="hero-body">
        <div class="columns">
          <div class="column has-text-centered">
            <span class="icon is-large">
              <i class="fa fa-server"></i>
            </span>
            <p>Store the message on the server</p>
          </div>
          <div class="column has-text-centered">
            <span class="icon is-large">
              <i class="fa fa-key"></i>
            </span>
            <p>Get a unique random key</p>
          </div>
          <div class="column has-text-centered">
            <span class="icon is-large">
              <i class="fa fa-send"></i>
            </span>
            <p>Send the key to others</p>
          </div>
          <div class="column has-text-centered">
            <span class="icon is-large">
              <i class="fa fa-envelope"></i>
            </span>
            <p>Retrieve the message</p>
          </div>
          <div class="column has-text-centered">
            <span class="icon is-large">
              <i class="fa fa-trash"></i>
            </span>
            <p>The message is deleted</p>
          </div>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">
        <h1 class="title">Sending</h1>
        <h2 class="subtitle">As easy as copy and paste</h2>
        <hr>
        <div class="content">
          <p>Sending the message consists of two easy steps:</p>
          <ol>
            <li>Compose the message you want to send to others.</li>
            <li>Copy the autogenerated key to others.</li>
          </ol>
          <p>That's it! The receiver can now retrieve the message using that key.</p>
        </div>
        <hr>
      </div>
    </section>
    <section class="section">
      <div class="container">
        <h1 class="title">Receiving</h1>
        <h2 class="subtitle">Get the message without leaving a trace</h2>
        <hr>
        <div class="content">
          <p>Similarly, receiving the message is very straightforward:</p>
          <ol>
            <li>Search for the message using the generated key</li>
            <li>The message is deleted on the server automatically</li>
          </ol>
          <p>The message stored on the server will also be deleted after 30 minutes if no one retrieves it.</p>
        </div>
        <hr>
      </div>
    </section>
    <section class="hero has-text-centered is-medium">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">Get Started</h1>
          <div class="hero-buttons">
            <router-link :to="{ name: 'Dashboard' }" class="button is-medium is-primary">Dashboard</router-link>
            <a href="https://github.com/JokeyChen/messagehub" class="button is-medium">View Source</a>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
export default {
}
</script>

<style>
</style>
